/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Barang;
import service.BarangService;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import java.util.List;
/**
 *
 * @author user
 */
public class BarangForm extends javax.swing.JFrame {
    
    private BarangService barangService = new BarangService();
    private DefaultTableModel modelBarang;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BarangForm.class.getName());

    /**
     * Creates new form BarangForm
     */
    public BarangForm() {
        initComponents();
        setLocationRelativeTo(null);
        setupTabelBarang();
        muatSemuaBarang();
        pasangLiveSearch();
    }
    
    private void setupTabelBarang() {
        String[] kolom = {"Barcode", "Nama Barang", "Kategori", "Harga Beli", "Harga Jual", "Stok", "Satuan"};
        modelBarang = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // semua kolom read-only
            }
        };
        tblBarang.setModel(modelBarang);
    }

    private void muatSemuaBarang() {
        try {
            List<Barang> daftarBarang = barangService.ambilSemuaBarang();
            tampilkanKeTabel(daftarBarang);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal memuat data barang: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tampilkanKeTabel(List<Barang> daftarBarang) {
        modelBarang.setRowCount(0); // kosongkan tabel dulu
        for (Barang b : daftarBarang) {
            modelBarang.addRow(new Object[]{
                    b.getBarcode(),
                    b.getNamaBarang(),
                    b.getKategori(),
                    b.getHargaBeli(),
                    b.getHargaJual(),
                    b.getStok(),
                    b.getSatuan()
            });
        }
        lblJumlahData.setText("Menampilkan " + daftarBarang.size() + " data barang");
    }    
    
    private void pasangLiveSearch() {
        txtCariBarang.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { cariBarangSekarang(); }
            @Override
            public void removeUpdate(DocumentEvent e) { cariBarangSekarang(); }
            @Override
            public void changedUpdate(DocumentEvent e) { cariBarangSekarang(); }
        });
    }

    private void cariBarangSekarang() {
        String keyword = txtCariBarang.getText().trim();
        try {
            List<Barang> hasil = keyword.isEmpty()
                    ? barangService.ambilSemuaBarang()
                    : barangService.cariBarang(keyword);
            tampilkanKeTabel(hasil);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal mencari barang: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeaderBarang = new javax.swing.JPanel();
        lblJudulBarang = new javax.swing.JLabel();
        btnTutupBarang = new javax.swing.JButton();
        panelBodyBarang = new javax.swing.JPanel();
        panelToolbarBarang = new javax.swing.JPanel();
        panelSearchToolbar = new javax.swing.JPanel();
        txtCariBarang = new javax.swing.JTextField();
        btnCariBarang = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        panelAksiToolbar = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        scrollBarang = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        lblJumlahData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Barang - Sistem POS Toko Pardono");
        setBackground(new java.awt.Color(243, 244, 246));
        setSize(new java.awt.Dimension(1000, 650));

        panelHeaderBarang.setBackground(new java.awt.Color(255, 255, 255));
        panelHeaderBarang.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20), javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(209, 213, 219))));
        panelHeaderBarang.setLayout(new java.awt.BorderLayout());

        lblJudulBarang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudulBarang.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulBarang.setText("DATA BARANG");
        panelHeaderBarang.add(lblJudulBarang, java.awt.BorderLayout.WEST);

        btnTutupBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTutupBarang.setForeground(new java.awt.Color(107, 114, 128));
        btnTutupBarang.setText("[x]");
        btnTutupBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTutupBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTutupBarang.setFocusable(false);
        btnTutupBarang.setPreferredSize(new java.awt.Dimension(32, 32));
        btnTutupBarang.addActionListener(this::btnTutupBarangActionPerformed);
        panelHeaderBarang.add(btnTutupBarang, java.awt.BorderLayout.EAST);

        getContentPane().add(panelHeaderBarang, java.awt.BorderLayout.NORTH);

        panelBodyBarang.setBackground(new java.awt.Color(243, 244, 246));
        panelBodyBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        panelBodyBarang.setLayout(new java.awt.BorderLayout());

        panelToolbarBarang.setBackground(new java.awt.Color(255, 255, 255));
        panelToolbarBarang.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235))));
        panelToolbarBarang.setLayout(new java.awt.BorderLayout());

        panelSearchToolbar.setBackground(new java.awt.Color(255, 255, 255));
        panelSearchToolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 0));

        txtCariBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        txtCariBarang.setPreferredSize(new java.awt.Dimension(280, 34));
        panelSearchToolbar.add(txtCariBarang);

        btnCariBarang.setBackground(new java.awt.Color(37, 99, 235));
        btnCariBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnCariBarang.setText("Cari");
        btnCariBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCariBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCariBarang.setFocusable(false);
        btnCariBarang.setPreferredSize(new java.awt.Dimension(80, 34));
        btnCariBarang.addActionListener(this::btnCariBarangActionPerformed);
        panelSearchToolbar.add(btnCariBarang);

        btnRefresh.setBackground(new java.awt.Color(243, 244, 246));
        btnRefresh.setForeground(new java.awt.Color(55, 65, 81));
        btnRefresh.setText("↻ Refresh");
        btnRefresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.setFocusable(false);
        btnRefresh.setPreferredSize(new java.awt.Dimension(100, 34));
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        panelSearchToolbar.add(btnRefresh);

        panelToolbarBarang.add(panelSearchToolbar, java.awt.BorderLayout.WEST);

        panelAksiToolbar.setBackground(new java.awt.Color(255, 255, 255));
        panelAksiToolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 0));

        btnTambah.setBackground(new java.awt.Color(22, 163, 74));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah Barang");
        btnTambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.setFocusable(false);
        btnTambah.setPreferredSize(new java.awt.Dimension(140, 34));
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        panelAksiToolbar.add(btnTambah);

        btnEdit.setBackground(new java.awt.Color(37, 99, 235));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusable(false);
        btnEdit.setPreferredSize(new java.awt.Dimension(80, 34));
        btnEdit.addActionListener(this::btnEditActionPerformed);
        panelAksiToolbar.add(btnEdit);

        btnHapus.setBackground(new java.awt.Color(220, 38, 38));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.setFocusable(false);
        btnHapus.setPreferredSize(new java.awt.Dimension(80, 34));
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        panelAksiToolbar.add(btnHapus);

        btnImport.setBackground(new java.awt.Color(243, 244, 246));
        btnImport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImport.setForeground(new java.awt.Color(55, 65, 81));
        btnImport.setText("Import");
        btnImport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        btnImport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImport.setFocusable(false);
        btnImport.setPreferredSize(new java.awt.Dimension(90, 34));
        btnImport.addActionListener(this::btnImportActionPerformed);
        panelAksiToolbar.add(btnImport);

        btnExport.setBackground(new java.awt.Color(243, 244, 246));
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExport.setForeground(new java.awt.Color(55, 65, 81));
        btnExport.setText("Export");
        btnExport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        btnExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExport.setFocusable(false);
        btnExport.setPreferredSize(new java.awt.Dimension(90, 34));
        btnExport.addActionListener(this::btnExportActionPerformed);
        panelAksiToolbar.add(btnExport);

        panelToolbarBarang.add(panelAksiToolbar, java.awt.BorderLayout.EAST);

        panelBodyBarang.add(panelToolbarBarang, java.awt.BorderLayout.NORTH);

        scrollBarang.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(15, 0, 0, 0));

        tblBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));
        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.setGridColor(new java.awt.Color(229, 231, 235));
        tblBarang.setRowHeight(30);
        tblBarang.setSelectionBackground(new java.awt.Color(219, 234, 254));
        scrollBarang.setViewportView(tblBarang);

        panelBodyBarang.add(scrollBarang, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBodyBarang, java.awt.BorderLayout.CENTER);

        lblJumlahData.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblJumlahData.setForeground(new java.awt.Color(107, 114, 128));
        lblJumlahData.setText("Menampilkan 0 Data Barang");
        lblJumlahData.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 20, 8, 20));
        getContentPane().add(lblJumlahData, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBarangActionPerformed
        // TODO add your handling code here:
        cariBarangSekarang();
    }//GEN-LAST:event_btnCariBarangActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtCariBarang.setText("");
        muatSemuaBarang();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        FormTambahEditBarang form = new FormTambahEditBarang(null);
        form.setLocationRelativeTo(this);
        form.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (form.isSimpanDiklik()) {
                    try {
                        barangService.tambahBarang(form.getBarangHasil());
                        JOptionPane.showMessageDialog(BarangForm.this, "Barang berhasil ditambahkan!");
                        muatSemuaBarang();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(BarangForm.this,
                                "Gagal menambah barang: " + ex.getMessage(),
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
        form.setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int baris = tblBarang.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih dulu barang yang ingin diedit!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String barcode = (String) modelBarang.getValueAt(baris, 0);
            List<Barang> hasil = barangService.cariBarang(barcode);
            if (hasil.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Data barang tidak ditemukan.");
                return;
            }
            Barang barangTerpilih = hasil.get(0);

            FormTambahEditBarang form = new FormTambahEditBarang(barangTerpilih);
            form.setLocationRelativeTo(this);

            // Pengecekan simpan dipindah ke sini, baru jalan SETELAH form ditutup
            form.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    if (form.isSimpanDiklik()) {
                        try {
                            barangService.updateBarang(form.getBarangHasil());
                            JOptionPane.showMessageDialog(BarangForm.this, "Barang berhasil diperbarui!");
                            muatSemuaBarang();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(BarangForm.this,
                                    "Gagal mengedit barang: " + ex.getMessage(),
                                    "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            });

            form.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal mengambil data barang: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int baris = tblBarang.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih dulu barang yang ingin dihapus!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus barang ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                String barcode = (String) modelBarang.getValueAt(baris, 0);
                List<Barang> hasil = barangService.cariBarang(barcode);
                if (!hasil.isEmpty()) {
                    barangService.hapusBarang(hasil.get(0).getIdBarang());
                    JOptionPane.showMessageDialog(this, "Barang berhasil dihapus!");
                    muatSemuaBarang();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Gagal menghapus barang: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
            "Fitur Import akan tersedia pada update berikutnya.",
            "Info",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
            "Fitur Export akan tersedia pada update berikutnya.",
            "Info",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnTutupBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupBarangActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnTutupBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BarangForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariBarang;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTutupBarang;
    private javax.swing.JLabel lblJudulBarang;
    private javax.swing.JLabel lblJumlahData;
    private javax.swing.JPanel panelAksiToolbar;
    private javax.swing.JPanel panelBodyBarang;
    private javax.swing.JPanel panelHeaderBarang;
    private javax.swing.JPanel panelSearchToolbar;
    private javax.swing.JPanel panelToolbarBarang;
    private javax.swing.JScrollPane scrollBarang;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtCariBarang;
    // End of variables declaration//GEN-END:variables
}
