/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.event.*;
import model.Pengguna;
import service.KasirService;
/**
 *
 * @author user
 */
public class Dasboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dasboard.class.getName());
    private Pengguna userLogin;
    private KasirService kasirService;
    private Timer timerWaktu;
    /**
     * Creates new form Dasboard
     */
    public Dasboard(Pengguna userLogin) {
        initComponents();
        this.userLogin = userLogin;
        this.kasirService = new KasirService();
        setLocationRelativeTo(null);

        // FIX: sebelumnya nama & role di header selalu menampilkan teks statis
        // "Selamat Datang, Admin" / "Role: Admin" bawaan GUI Builder, tidak
        // pernah diganti sesuai siapa yang login. Sekarang diambil dari objek
        // userLogin yang sebenarnya (bisa Admin atau Kasir - POLYMORPHISM).
        lblSelamatDatang.setText("Selamat Datang, " + userLogin.getNama());
        lblRole.setText("Role: " + userLogin.getLabelHakAkses());

        // FIX: sebelumnya semua 6 menu selalu tampil untuk siapa saja.
        // Sekarang menu disembunyikan/nonaktifkan jika role yang login
        // tidak berhak mengaksesnya, murni lewat userLogin.bolehAkses(...)
        // TANPA instanceof - inilah POLYMORPHISM: hasil berbeda tergantung
        // objek asli (Admin/Kasir) walau method yang dipanggil sama persis.
        aturHakAksesMenu();
    }

    /**
     * Menyembunyikan panel menu yang tidak boleh diakses oleh role
     * pengguna yang sedang login.
     */
    private void aturHakAksesMenu() {
        aturVisibilitasMenu(panelMenuDataUser, "DATA_USER");
        aturVisibilitasMenu(panelMenuDataBarang, "DATA_BARANG");
        aturVisibilitasMenu(panelMenuKasir, "KASIR");
        aturVisibilitasMenu(panelMenuLaporan, "LAPORAN");
        aturVisibilitasMenu(panelMenuBackup, "BACKUP");
        aturVisibilitasMenu(panelMenuRestore, "RESTORE");
    }

    private void aturVisibilitasMenu(javax.swing.JPanel panelMenu, String kodeMenu) {
        boolean boleh = userLogin.bolehAkses(kodeMenu);
        panelMenu.setVisible(boleh);
        panelMenu.setEnabled(boleh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeaderWrapper = new javax.swing.JPanel();
        panelHeaderDasboard = new javax.swing.JPanel();
        panelKolomKiri = new javax.swing.JPanel();
        lblNamaToko = new javax.swing.JLabel();
        lblTanggalWaktu = new javax.swing.JLabel();
        panelInfoUser = new javax.swing.JPanel();
        panelBarisUser1 = new javax.swing.JPanel();
        lblSelamatDatang = new javax.swing.JLabel();
        btnSetting = new javax.swing.JButton();
        panelBarisUser2 = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        sepHeader = new javax.swing.JSeparator();
        panelBodyMenu = new javax.swing.JPanel();
        panelMenuDataUser = new javax.swing.JPanel();
        lblJudulDataUser = new javax.swing.JLabel();
        lblSubDataUser = new javax.swing.JLabel();
        panelMenuDataBarang = new javax.swing.JPanel();
        lblJudulDataBarang = new javax.swing.JLabel();
        lblSubDataBarang = new javax.swing.JLabel();
        panelMenuKasir = new javax.swing.JPanel();
        lblJudulKasir = new javax.swing.JLabel();
        lblSubKasir = new javax.swing.JLabel();
        panelMenuLaporan = new javax.swing.JPanel();
        lblJudulLaporan = new javax.swing.JLabel();
        lblSubLaporan = new javax.swing.JLabel();
        panelMenuBackup = new javax.swing.JPanel();
        lblJudulBackup = new javax.swing.JLabel();
        lblSubBackup = new javax.swing.JLabel();
        panelMenuRestore = new javax.swing.JPanel();
        lblJudulRestore = new javax.swing.JLabel();
        lblSubRestore = new javax.swing.JLabel();
        panelFooterStatistik = new javax.swing.JPanel();
        lblJudulStatistik = new javax.swing.JLabel();
        panelDataStatistik = new javax.swing.JPanel();
        lblTotalTransaksi = new javax.swing.JLabel();
        lblTotalPenjualan = new javax.swing.JLabel();
        lblBarangTerjual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DASHBOARD - SISTEM POS TOKO PARDONO");
        setBackground(new java.awt.Color(243, 244, 246));
        setSize(new java.awt.Dimension(900, 650));

        panelHeaderWrapper.setLayout(new javax.swing.BoxLayout(panelHeaderWrapper, javax.swing.BoxLayout.Y_AXIS));

        panelHeaderDasboard.setBackground(new java.awt.Color(255, 255, 255));
        panelHeaderDasboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 10, 20));
        panelHeaderDasboard.setPreferredSize(new java.awt.Dimension(900, 90));
        panelHeaderDasboard.setLayout(new java.awt.BorderLayout());

        panelKolomKiri.setBackground(new java.awt.Color(255, 255, 255));
        panelKolomKiri.setLayout(new javax.swing.BoxLayout(panelKolomKiri, javax.swing.BoxLayout.Y_AXIS));

        lblNamaToko.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNamaToko.setForeground(new java.awt.Color(17, 24, 39));
        lblNamaToko.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNamaToko.setText("TOKO PARDONO - SISTEM POS");
        lblNamaToko.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelKolomKiri.add(lblNamaToko);

        lblTanggalWaktu.setForeground(new java.awt.Color(107, 114, 128));
        lblTanggalWaktu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTanggalWaktu.setText("Senin, 15 Januari 2024 14:30");
        lblTanggalWaktu.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 0, 0));
        panelKolomKiri.add(lblTanggalWaktu);

        panelHeaderDasboard.add(panelKolomKiri, java.awt.BorderLayout.WEST);

        panelInfoUser.setBackground(new java.awt.Color(255, 255, 255));
        panelInfoUser.setLayout(new javax.swing.BoxLayout(panelInfoUser, javax.swing.BoxLayout.Y_AXIS));

        panelBarisUser1.setBackground(new java.awt.Color(255, 255, 255));
        panelBarisUser1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 0));

        lblSelamatDatang.setForeground(new java.awt.Color(55, 65, 81));
        lblSelamatDatang.setText("Selamat Datang, Admin");
        panelBarisUser1.add(lblSelamatDatang);

        btnSetting.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(55, 65, 81));
        btnSetting.setText("[Setting]");
        btnSetting.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetting.setFocusable(false);
        btnSetting.setPreferredSize(new java.awt.Dimension(70, 24));
        btnSetting.addActionListener(this::btnSettingActionPerformed);
        panelBarisUser1.add(btnSetting);

        panelInfoUser.add(panelBarisUser1);

        panelBarisUser2.setBackground(new java.awt.Color(255, 255, 255));
        panelBarisUser2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 0));

        lblRole.setForeground(new java.awt.Color(55, 65, 81));
        lblRole.setText("Role: Admin");
        panelBarisUser2.add(lblRole);

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(220, 38, 38));
        btnLogout.setText("[Logout]");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusable(false);
        btnLogout.setPreferredSize(new java.awt.Dimension(70, 24));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        panelBarisUser2.add(btnLogout);

        panelInfoUser.add(panelBarisUser2);

        panelHeaderDasboard.add(panelInfoUser, java.awt.BorderLayout.EAST);

        panelHeaderWrapper.add(panelHeaderDasboard);

        sepHeader.setForeground(new java.awt.Color(209, 213, 219));
        panelHeaderWrapper.add(sepHeader);

        getContentPane().add(panelHeaderWrapper, java.awt.BorderLayout.NORTH);

        panelBodyMenu.setBackground(new java.awt.Color(243, 244, 246));
        panelBodyMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 20, 25, 20));
        panelBodyMenu.setLayout(new java.awt.GridLayout(2, 3, 20, 20));

        panelMenuDataUser.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuDataUser.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235))));
        panelMenuDataUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuDataUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuDataUserMouseClicked(evt);
            }
        });
        panelMenuDataUser.setLayout(new javax.swing.BoxLayout(panelMenuDataUser, javax.swing.BoxLayout.Y_AXIS));

        lblJudulDataUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudulDataUser.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulDataUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulDataUser.setText("DATA USER");
        lblJudulDataUser.setAlignmentX(0.5F);
        panelMenuDataUser.add(lblJudulDataUser);

        lblSubDataUser.setForeground(new java.awt.Color(107, 114, 128));
        lblSubDataUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubDataUser.setText("Kelola User");
        lblSubDataUser.setAlignmentX(0.5F);
        lblSubDataUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 0, 0, 0));
        panelMenuDataUser.add(lblSubDataUser);

        panelBodyMenu.add(panelMenuDataUser);

        panelMenuDataBarang.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuDataBarang.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235))));
        panelMenuDataBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuDataBarangMouseClicked(evt);
            }
        });
        panelMenuDataBarang.setLayout(new javax.swing.BoxLayout(panelMenuDataBarang, javax.swing.BoxLayout.Y_AXIS));

        lblJudulDataBarang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudulDataBarang.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulDataBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulDataBarang.setText("DATA BARANG");
        lblJudulDataBarang.setAlignmentX(0.5F);
        panelMenuDataBarang.add(lblJudulDataBarang);

        lblSubDataBarang.setForeground(new java.awt.Color(107, 114, 128));
        lblSubDataBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubDataBarang.setText("Kelola Barang");
        lblSubDataBarang.setAlignmentX(0.5F);
        lblSubDataBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 0, 0, 0));
        panelMenuDataBarang.add(lblSubDataBarang);

        panelBodyMenu.add(panelMenuDataBarang);

        panelMenuKasir.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuKasir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235))));
        panelMenuKasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuKasirMouseClicked(evt);
            }
        });
        panelMenuKasir.setLayout(new javax.swing.BoxLayout(panelMenuKasir, javax.swing.BoxLayout.Y_AXIS));

        lblJudulKasir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudulKasir.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulKasir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulKasir.setText("KASIR");
        lblJudulKasir.setAlignmentX(0.5F);
        panelMenuKasir.add(lblJudulKasir);

        lblSubKasir.setForeground(new java.awt.Color(107, 114, 128));
        lblSubKasir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubKasir.setText("Transaksi");
        lblSubKasir.setAlignmentX(0.5F);
        lblSubKasir.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 0, 0, 0));
        panelMenuKasir.add(lblSubKasir);

        panelBodyMenu.add(panelMenuKasir);

        panelMenuLaporan.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuLaporan.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235))));
        panelMenuLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuLaporanMouseClicked(evt);
            }
        });
        panelMenuLaporan.setLayout(new javax.swing.BoxLayout(panelMenuLaporan, javax.swing.BoxLayout.Y_AXIS));

        lblJudulLaporan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudulLaporan.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulLaporan.setText("LAPORAN");
        lblJudulLaporan.setAlignmentX(0.5F);
        panelMenuLaporan.add(lblJudulLaporan);

        lblSubLaporan.setForeground(new java.awt.Color(107, 114, 128));
        lblSubLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubLaporan.setText("Penjualan");
        lblSubLaporan.setAlignmentX(0.5F);
        lblSubLaporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 0, 0, 0));
        panelMenuLaporan.add(lblSubLaporan);

        panelBodyMenu.add(panelMenuLaporan);

        panelMenuBackup.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuBackup.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235))));
        panelMenuBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuBackupMouseClicked(evt);
            }
        });
        panelMenuBackup.setLayout(new javax.swing.BoxLayout(panelMenuBackup, javax.swing.BoxLayout.Y_AXIS));

        lblJudulBackup.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudulBackup.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulBackup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulBackup.setText("BACKUP");
        lblJudulBackup.setAlignmentX(0.5F);
        panelMenuBackup.add(lblJudulBackup);

        lblSubBackup.setForeground(new java.awt.Color(107, 114, 128));
        lblSubBackup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubBackup.setText("Database");
        lblSubBackup.setAlignmentX(0.5F);
        lblSubBackup.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 0, 0, 0));
        panelMenuBackup.add(lblSubBackup);

        panelBodyMenu.add(panelMenuBackup);

        panelMenuRestore.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuRestore.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235))));
        panelMenuRestore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuRestoreMouseClicked(evt);
            }
        });
        panelMenuRestore.setLayout(new javax.swing.BoxLayout(panelMenuRestore, javax.swing.BoxLayout.Y_AXIS));

        lblJudulRestore.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudulRestore.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulRestore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulRestore.setText("RESTORE");
        lblJudulRestore.setAlignmentX(0.5F);
        panelMenuRestore.add(lblJudulRestore);

        lblSubRestore.setForeground(new java.awt.Color(107, 114, 128));
        lblSubRestore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubRestore.setText("Database");
        lblSubRestore.setAlignmentX(0.5F);
        lblSubRestore.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 0, 0, 0));
        panelMenuRestore.add(lblSubRestore);

        panelBodyMenu.add(panelMenuRestore);

        getContentPane().add(panelBodyMenu, java.awt.BorderLayout.CENTER);

        panelFooterStatistik.setBackground(new java.awt.Color(255, 255, 255));
        panelFooterStatistik.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20), javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(209, 213, 219))));
        panelFooterStatistik.setPreferredSize(new java.awt.Dimension(900, 110));
        panelFooterStatistik.setLayout(new java.awt.BorderLayout());

        lblJudulStatistik.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblJudulStatistik.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulStatistik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudulStatistik.setText("STATISTIK HARI INI");
        lblJudulStatistik.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        panelFooterStatistik.add(lblJudulStatistik, java.awt.BorderLayout.NORTH);

        panelDataStatistik.setBackground(new java.awt.Color(255, 255, 255));
        panelDataStatistik.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 40, 0));

        lblTotalTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTotalTransaksi.setForeground(new java.awt.Color(55, 65, 81));
        lblTotalTransaksi.setText("Total Transaksi: 25");
        panelDataStatistik.add(lblTotalTransaksi);

        lblTotalPenjualan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTotalPenjualan.setForeground(new java.awt.Color(55, 65, 81));
        lblTotalPenjualan.setText("Total Penjualan: Rp 500.000");
        panelDataStatistik.add(lblTotalPenjualan);

        lblBarangTerjual.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblBarangTerjual.setForeground(new java.awt.Color(55, 65, 81));
        lblBarangTerjual.setText("Barang terjual: 150 pcs");
        panelDataStatistik.add(lblBarangTerjual);

        panelFooterStatistik.add(panelDataStatistik, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelFooterStatistik, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
            this,
            "Fitur Setting akan tersedia pada update berikutnya.",
            "Info",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            if (timerWaktu != null) {
                timerWaktu.stop();
            }
            this.dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void panelMenuDataUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuDataUserMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
            this,
            "Fitur Data User akan tersedia pada update berikutnya.",
            "Info",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_panelMenuDataUserMouseClicked

    private void panelMenuDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuDataBarangMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
            this,
            "Fitur Data Barang akan tersedia pada update berikutnya.",
            "Info",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_panelMenuDataBarangMouseClicked

    private void panelMenuKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuKasirMouseClicked
        // TODO add your handling code here:
        new KasirForm(userLogin).setVisible(true);
    }//GEN-LAST:event_panelMenuKasirMouseClicked

    private void panelMenuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuLaporanMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
            this,
            "Fitur Laporan akan tersedia pada update berikutnya.",
            "Info",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_panelMenuLaporanMouseClicked

    private void panelMenuBackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuBackupMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
            this,
            "Fitur Backup Database akan tersedia pada update berikutnya.",
            "Info",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_panelMenuBackupMouseClicked

    private void panelMenuRestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuRestoreMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
            this,
            "Fitur Restore Database akan tersedia pada update berikutnya.",
            "Info",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_panelMenuRestoreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Buat dummy user untuk testing (karena Dashboard butuh parameter Pengguna)
                model.Pengguna dummyUser = new model.Admin(
                    1,                  // idUser
                    "admin",            // username
                    "admin123",         // password
                    "Admin Testing",    // nama
                    "ADMIN"             // role
                );
            
                // Buka Dashboard dengan dummy user
                Dasboard dashboard = new Dasboard(dummyUser);
                dashboard.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSetting;
    private javax.swing.JLabel lblBarangTerjual;
    private javax.swing.JLabel lblJudulBackup;
    private javax.swing.JLabel lblJudulDataBarang;
    private javax.swing.JLabel lblJudulDataUser;
    private javax.swing.JLabel lblJudulKasir;
    private javax.swing.JLabel lblJudulLaporan;
    private javax.swing.JLabel lblJudulRestore;
    private javax.swing.JLabel lblJudulStatistik;
    private javax.swing.JLabel lblNamaToko;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSelamatDatang;
    private javax.swing.JLabel lblSubBackup;
    private javax.swing.JLabel lblSubDataBarang;
    private javax.swing.JLabel lblSubDataUser;
    private javax.swing.JLabel lblSubKasir;
    private javax.swing.JLabel lblSubLaporan;
    private javax.swing.JLabel lblSubRestore;
    private javax.swing.JLabel lblTanggalWaktu;
    private javax.swing.JLabel lblTotalPenjualan;
    private javax.swing.JLabel lblTotalTransaksi;
    private javax.swing.JPanel panelBarisUser1;
    private javax.swing.JPanel panelBarisUser2;
    private javax.swing.JPanel panelBodyMenu;
    private javax.swing.JPanel panelDataStatistik;
    private javax.swing.JPanel panelFooterStatistik;
    private javax.swing.JPanel panelHeaderDasboard;
    private javax.swing.JPanel panelHeaderWrapper;
    private javax.swing.JPanel panelInfoUser;
    private javax.swing.JPanel panelKolomKiri;
    private javax.swing.JPanel panelMenuBackup;
    private javax.swing.JPanel panelMenuDataBarang;
    private javax.swing.JPanel panelMenuDataUser;
    private javax.swing.JPanel panelMenuKasir;
    private javax.swing.JPanel panelMenuLaporan;
    private javax.swing.JPanel panelMenuRestore;
    private javax.swing.JSeparator sepHeader;
    // End of variables declaration//GEN-END:variables
}
