/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Barang;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class FormTambahEditBarang extends javax.swing.JFrame {
    
    private boolean simpanDiklik = false;
    private Barang barangEdit;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTambahEditBarang.class.getName());

    /**
     * Creates new form FormTambahEditBarang
     */
    public FormTambahEditBarang(Barang barangEdit) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.barangEdit = barangEdit;

        if (barangEdit == null) {
            // MODE TAMBAH
            lblJudulFormBarang.setText("Tambah Barang Baru");
            setTitle("Tambah Barang Baru - Sistem POS Toko Pardono");
        } else {
            // MODE EDIT — isi semua field dari data barang yang mau diedit
            lblJudulFormBarang.setText("Edit Barang");
            setTitle("Edit Barang - Sistem POS Toko Pardono");

            txtBarcode.setText(barangEdit.getBarcode());
            txtNamaBarang.setText(barangEdit.getNamaBarang());
            cmbKategori.setSelectedItem(barangEdit.getKategori());
            txtHargaBeli.setText(String.valueOf(barangEdit.getHargaBeli()));
            txtHargaJual.setText(String.valueOf(barangEdit.getHargaJual()));
            txtStok.setText(String.valueOf(barangEdit.getStok()));
            cmbSatuan.setSelectedItem(barangEdit.getSatuan());
        }
    }
    
    public boolean isSimpanDiklik() {
        return simpanDiklik;
    }

    public Barang getBarangHasil() {
        Barang b = (barangEdit != null) ? barangEdit : new Barang();
        b.setBarcode(txtBarcode.getText().trim());
        b.setNamaBarang(txtNamaBarang.getText().trim());
        b.setKategori((String) cmbKategori.getSelectedItem());
        b.setHargaBeli(Double.parseDouble(txtHargaBeli.getText().trim()));
        b.setHargaJual(Double.parseDouble(txtHargaJual.getText().trim()));
        b.setStok(Integer.parseInt(txtStok.getText().trim()));
        b.setSatuan((String) cmbSatuan.getSelectedItem());
        return b;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeaderTambahBarang = new javax.swing.JPanel();
        lblJudulFormBarang = new javax.swing.JLabel();
        panelFormBarang = new javax.swing.JPanel();
        lblBarcode = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        lblNamaBarang = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        lblKategori = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox<>();
        lblHargaBeli = new javax.swing.JLabel();
        txtHargaBeli = new javax.swing.JTextField();
        lblHargaJual = new javax.swing.JLabel();
        txtHargaJual = new javax.swing.JTextField();
        lblStok = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        lblSatuan = new javax.swing.JLabel();
        cmbSatuan = new javax.swing.JComboBox<>();
        panelAksiFormBarang = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Barang Baru - Sistem POS Toko Pardono");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 600));

        panelHeaderTambahBarang.setBackground(new java.awt.Color(255, 255, 255));
        panelHeaderTambahBarang.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 15, 20), javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(209, 213, 219))));
        panelHeaderTambahBarang.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        lblJudulFormBarang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudulFormBarang.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulFormBarang.setText("Tambah Barang Baru");
        panelHeaderTambahBarang.add(lblJudulFormBarang);

        getContentPane().add(panelHeaderTambahBarang, java.awt.BorderLayout.NORTH);

        panelFormBarang.setBackground(new java.awt.Color(255, 255, 255));
        panelFormBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));

        lblBarcode.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblBarcode.setForeground(new java.awt.Color(55, 65, 81));
        lblBarcode.setText("Barcode");

        txtBarcode.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtBarcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        txtBarcode.setPreferredSize(new java.awt.Dimension(380, 36));

        lblNamaBarang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNamaBarang.setForeground(new java.awt.Color(55, 65, 81));
        lblNamaBarang.setText("Nama Barang");

        txtNamaBarang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtNamaBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        txtNamaBarang.setPreferredSize(new java.awt.Dimension(380, 36));

        lblKategori.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblKategori.setForeground(new java.awt.Color(55, 65, 81));
        lblKategori.setText("Kategori");

        cmbKategori.setEditable(true);
        cmbKategori.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Sembako", "Lainnya" }));
        cmbKategori.setPreferredSize(new java.awt.Dimension(380, 36));

        lblHargaBeli.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHargaBeli.setForeground(new java.awt.Color(55, 65, 81));
        lblHargaBeli.setText("Harga Beli");

        txtHargaBeli.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtHargaBeli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        txtHargaBeli.setPreferredSize(new java.awt.Dimension(380, 36));

        lblHargaJual.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHargaJual.setForeground(new java.awt.Color(55, 65, 81));
        lblHargaJual.setText("Harga Jual");

        txtHargaJual.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtHargaJual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        txtHargaJual.setPreferredSize(new java.awt.Dimension(380, 36));

        lblStok.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblStok.setForeground(new java.awt.Color(55, 65, 81));
        lblStok.setText("Stok");

        txtStok.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtStok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        txtStok.setPreferredSize(new java.awt.Dimension(380, 36));

        lblSatuan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSatuan.setForeground(new java.awt.Color(55, 65, 81));
        lblSatuan.setText("Satuan");

        cmbSatuan.setEditable(true);
        cmbSatuan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pcs", "botol", "karung", "renceng", "dus" }));
        cmbSatuan.setPreferredSize(new java.awt.Dimension(380, 36));

        javax.swing.GroupLayout panelFormBarangLayout = new javax.swing.GroupLayout(panelFormBarang);
        panelFormBarang.setLayout(panelFormBarangLayout);
        panelFormBarangLayout.setHorizontalGroup(
            panelFormBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormBarangLayout.createSequentialGroup()
                .addComponent(lblBarcode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelFormBarangLayout.createSequentialGroup()
                .addComponent(lblNamaBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelFormBarangLayout.createSequentialGroup()
                .addComponent(lblKategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelFormBarangLayout.createSequentialGroup()
                .addComponent(lblHargaBeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelFormBarangLayout.createSequentialGroup()
                .addComponent(lblHargaJual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelFormBarangLayout.createSequentialGroup()
                .addComponent(lblStok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelFormBarangLayout.createSequentialGroup()
                .addComponent(lblSatuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelFormBarangLayout.setVerticalGroup(
            panelFormBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormBarangLayout.createSequentialGroup()
                .addGroup(panelFormBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarcode)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelFormBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaBarang)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelFormBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKategori))
                .addGap(10, 10, 10)
                .addGroup(panelFormBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHargaBeli)
                    .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelFormBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHargaJual)
                    .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelFormBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStok)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelFormBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSatuan)))
        );

        getContentPane().add(panelFormBarang, java.awt.BorderLayout.CENTER);

        panelAksiFormBarang.setBackground(new java.awt.Color(255, 255, 255));
        panelAksiFormBarang.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20), javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(209, 213, 219))));
        panelAksiFormBarang.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0));

        btnBatal.setBackground(new java.awt.Color(243, 244, 246));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(55, 65, 81));
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.setFocusable(false);
        btnBatal.setPreferredSize(new java.awt.Dimension(100, 40));
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        panelAksiFormBarang.add(btnBatal);

        btnSimpan.setBackground(new java.awt.Color(37, 99, 235));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setFocusable(false);
        btnSimpan.setPreferredSize(new java.awt.Dimension(100, 40));
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        panelAksiFormBarang.add(btnSimpan);

        getContentPane().add(panelAksiFormBarang, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (txtBarcode.getText().trim().isEmpty()
            || txtNamaBarang.getText().trim().isEmpty()
            || txtHargaBeli.getText().trim().isEmpty()
            || txtHargaJual.getText().trim().isEmpty()
            || txtStok.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Semua field wajib diisi!",
                    "Validasi Gagal",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Double.parseDouble(txtHargaBeli.getText().trim());
            Double.parseDouble(txtHargaJual.getText().trim());
            Integer.parseInt(txtStok.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Harga Beli, Harga Jual, dan Stok harus berupa angka!",
                    "Validasi Gagal",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        simpanDiklik = true;
        dispose();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        simpanDiklik = false;
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTambahEditBarang(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbSatuan;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblHargaBeli;
    private javax.swing.JLabel lblHargaJual;
    private javax.swing.JLabel lblJudulFormBarang;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JLabel lblSatuan;
    private javax.swing.JLabel lblStok;
    private javax.swing.JPanel panelAksiFormBarang;
    private javax.swing.JPanel panelFormBarang;
    private javax.swing.JPanel panelHeaderTambahBarang;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
