/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import service.LaporanService;
import model.ItemLaporan;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import java.util.Date;
import java.util.Calendar;
import java.util.List;
import java.text.NumberFormat;
import java.util.Locale;
/**
 *
 * @author user
 */
public class LaporanForm extends javax.swing.JFrame {
    
    private LaporanService laporanService = new LaporanService();
    private DefaultTableModel modelTerlaris;
    private DefaultTableModel modelSedikitTerjual;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LaporanForm.class.getName());

    /**
     * Creates new form LaporanForm
     */
    public LaporanForm() {
        initComponents();
        setLocationRelativeTo(null);
        setupSpinner();
        setupTabelLaporan();
    }
    
    private void setupSpinner() {
        // dateAwal & dateAkhir default: awal bulan ini s.d hari ini
        Calendar cal = Calendar.getInstance();
        Date hariIni = cal.getTime();
        cal.set(Calendar.DAY_OF_MONTH, 1);
        Date awalBulan = cal.getTime();

        dateAwal.setModel(new SpinnerDateModel(awalBulan, null, null, Calendar.DAY_OF_MONTH));
        dateAwal.setEditor(new javax.swing.JSpinner.DateEditor(dateAwal, "dd/MM/yyyy"));

        dateAkhir.setModel(new SpinnerDateModel(hariIni, null, null, Calendar.DAY_OF_MONTH));
        dateAkhir.setEditor(new javax.swing.JSpinner.DateEditor(dateAkhir, "dd/MM/yyyy"));
    }
    
    private void setupTabelLaporan() {
        String[] kolom = {"Nama Barang", "Qty Terjual", "Total Penjualan"};

        modelTerlaris = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        tblBarangTerlaris.setModel(modelTerlaris);

        modelSedikitTerjual = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        tblBarangSedikitTerjual.setModel(modelSedikitTerjual);
    }
    
    private void tampilkanLaporan(Date awal, Date akhir) {
        try {
            double[] ringkasan = laporanService.getRingkasan(awal, akhir);
            NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));

            lblJumlahTransaksi.setText("Jumlah Transaksi: " + (int) ringkasan[0]);
            lblTotalPenjualan.setText("Total Penjualan: " + rupiah.format(ringkasan[1]));

            List<ItemLaporan> terlaris = laporanService.getBarangTerlaris(awal, akhir);
            modelTerlaris.setRowCount(0);
            for (ItemLaporan item : terlaris) {
                modelTerlaris.addRow(new Object[]{
                        item.getNamaBarang(),
                        item.getTotalQtyTerjual(),
                        rupiah.format(item.getTotalPenjualan())
                });
            }

            List<ItemLaporan> sedikitTerjual = laporanService.getBarangPalingSedikitTerjual(awal, akhir);
            modelSedikitTerjual.setRowCount(0);
            for (ItemLaporan item : sedikitTerjual) {
                modelSedikitTerjual.addRow(new Object[]{
                        item.getNamaBarang(),
                        item.getTotalQtyTerjual(),
                        rupiah.format(item.getTotalPenjualan())
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Gagal Menampilkan Laporan",
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeaderWrapperLap = new javax.swing.JPanel();
        panelJudulLaporan = new javax.swing.JPanel();
        lblJudulLaporan = new javax.swing.JLabel();
        btnTutupLaporan = new javax.swing.JButton();
        panelFilterLaporan = new javax.swing.JPanel();
        btnFilterHari = new javax.swing.JButton();
        btnFilterMinggu = new javax.swing.JButton();
        btnFilterBulan = new javax.swing.JButton();
        lblDariTanggal = new javax.swing.JLabel();
        dateAwal = new javax.swing.JSpinner();
        lblSampaiTanggal = new javax.swing.JLabel();
        dateAkhir = new javax.swing.JSpinner();
        btnTampilkan = new javax.swing.JButton();
        panelBodyLaporan = new javax.swing.JPanel();
        panelRingkasanLap = new javax.swing.JPanel();
        lblJumlahTransaksi = new javax.swing.JLabel();
        lblTotalPenjualan = new javax.swing.JLabel();
        panelDuaTabel = new javax.swing.JPanel();
        panelTerlaris = new javax.swing.JPanel();
        lblJudulTerlaris = new javax.swing.JLabel();
        scrollTerlaris = new javax.swing.JScrollPane();
        tblBarangTerlaris = new javax.swing.JTable();
        panelSedikitTerjual = new javax.swing.JPanel();
        lblJudulSedikitTerjual = new javax.swing.JLabel();
        scrollSedikitTerjual = new javax.swing.JScrollPane();
        tblBarangSedikitTerjual = new javax.swing.JTable();
        panelAksiLaporan = new javax.swing.JPanel();
        btnCetak = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();
        btnTutupLaporanBawah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laporan Penjualan - Sistem POS Toko Pardono");
        setBackground(new java.awt.Color(243, 244, 246));
        setSize(new java.awt.Dimension(1100, 750));

        panelHeaderWrapperLap.setBackground(new java.awt.Color(255, 255, 255));
        panelHeaderWrapperLap.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20), javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(209, 213, 219))));
        panelHeaderWrapperLap.setLayout(new javax.swing.BoxLayout(panelHeaderWrapperLap, javax.swing.BoxLayout.Y_AXIS));

        panelJudulLaporan.setLayout(new java.awt.BorderLayout());

        lblJudulLaporan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudulLaporan.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulLaporan.setText("LAPORAN PENJUALAN");
        panelJudulLaporan.add(lblJudulLaporan, java.awt.BorderLayout.WEST);

        btnTutupLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTutupLaporan.setForeground(new java.awt.Color(107, 114, 128));
        btnTutupLaporan.setText("[x]");
        btnTutupLaporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTutupLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTutupLaporan.setFocusable(false);
        btnTutupLaporan.setPreferredSize(new java.awt.Dimension(32, 32));
        btnTutupLaporan.addActionListener(this::btnTutupLaporanActionPerformed);
        panelJudulLaporan.add(btnTutupLaporan, java.awt.BorderLayout.EAST);

        panelHeaderWrapperLap.add(panelJudulLaporan);

        panelFilterLaporan.setBackground(new java.awt.Color(255, 255, 255));
        panelFilterLaporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 0, 0, 0));
        panelFilterLaporan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));

        btnFilterHari.setBackground(new java.awt.Color(243, 244, 246));
        btnFilterHari.setForeground(new java.awt.Color(55, 65, 81));
        btnFilterHari.setText("Hari Ini");
        btnFilterHari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        btnFilterHari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilterHari.setPreferredSize(new java.awt.Dimension(90, 34));
        btnFilterHari.addActionListener(this::btnFilterHariActionPerformed);
        panelFilterLaporan.add(btnFilterHari);

        btnFilterMinggu.setBackground(new java.awt.Color(243, 244, 246));
        btnFilterMinggu.setForeground(new java.awt.Color(55, 65, 81));
        btnFilterMinggu.setText("Minggu Ini");
        btnFilterMinggu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        btnFilterMinggu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilterMinggu.setPreferredSize(new java.awt.Dimension(100, 34));
        btnFilterMinggu.addActionListener(this::btnFilterMingguActionPerformed);
        panelFilterLaporan.add(btnFilterMinggu);

        btnFilterBulan.setBackground(new java.awt.Color(243, 244, 246));
        btnFilterBulan.setForeground(new java.awt.Color(55, 65, 81));
        btnFilterBulan.setText("Bulan Ini");
        btnFilterBulan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        btnFilterBulan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilterBulan.setPreferredSize(new java.awt.Dimension(90, 34));
        btnFilterBulan.addActionListener(this::btnFilterBulanActionPerformed);
        panelFilterLaporan.add(btnFilterBulan);

        lblDariTanggal.setForeground(new java.awt.Color(55, 65, 81));
        lblDariTanggal.setText("Dari:");
        panelFilterLaporan.add(lblDariTanggal);

        dateAwal.setModel(new javax.swing.SpinnerDateModel());
        dateAwal.setPreferredSize(new java.awt.Dimension(120, 34));
        panelFilterLaporan.add(dateAwal);

        lblSampaiTanggal.setForeground(new java.awt.Color(55, 65, 81));
        lblSampaiTanggal.setText("Sampai:");
        panelFilterLaporan.add(lblSampaiTanggal);

        dateAkhir.setModel(new javax.swing.SpinnerDateModel());
        dateAkhir.setPreferredSize(new java.awt.Dimension(120, 34));
        panelFilterLaporan.add(dateAkhir);

        btnTampilkan.setBackground(new java.awt.Color(37, 99, 235));
        btnTampilkan.setForeground(new java.awt.Color(255, 255, 255));
        btnTampilkan.setText("Tampilkan");
        btnTampilkan.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnTampilkan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTampilkan.setPreferredSize(new java.awt.Dimension(100, 34));
        btnTampilkan.addActionListener(this::btnTampilkanActionPerformed);
        panelFilterLaporan.add(btnTampilkan);

        panelHeaderWrapperLap.add(panelFilterLaporan);

        getContentPane().add(panelHeaderWrapperLap, java.awt.BorderLayout.NORTH);

        panelBodyLaporan.setBackground(new java.awt.Color(243, 244, 246));
        panelBodyLaporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        panelBodyLaporan.setLayout(new java.awt.BorderLayout());

        panelRingkasanLap.setBackground(new java.awt.Color(255, 255, 255));
        panelRingkasanLap.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235))));
        panelRingkasanLap.setPreferredSize(new java.awt.Dimension(700, 60));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 40, 0);
        flowLayout1.setAlignOnBaseline(true);
        panelRingkasanLap.setLayout(flowLayout1);

        lblJumlahTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblJumlahTransaksi.setForeground(new java.awt.Color(17, 24, 39));
        lblJumlahTransaksi.setText("Jumlah Transaksi: 0");
        panelRingkasanLap.add(lblJumlahTransaksi);

        lblTotalPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTotalPenjualan.setForeground(new java.awt.Color(37, 99, 235));
        lblTotalPenjualan.setText("Total Penjualan: 0");
        panelRingkasanLap.add(lblTotalPenjualan);

        panelBodyLaporan.add(panelRingkasanLap, java.awt.BorderLayout.NORTH);

        panelDuaTabel.setBackground(new java.awt.Color(243, 244, 246));
        panelDuaTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 0, 0, 0));
        panelDuaTabel.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        panelTerlaris.setBackground(new java.awt.Color(255, 255, 255));
        panelTerlaris.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235))));
        panelTerlaris.setLayout(new java.awt.BorderLayout());

        lblJudulTerlaris.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblJudulTerlaris.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulTerlaris.setText("BARANG TERLARIS");
        lblJudulTerlaris.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 8, 0));
        panelTerlaris.add(lblJudulTerlaris, java.awt.BorderLayout.NORTH);

        tblBarangTerlaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Barang", "Qty Terjual", "Total Penjualan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBarangTerlaris.setGridColor(new java.awt.Color(229, 231, 235));
        tblBarangTerlaris.setRowHeight(28);
        scrollTerlaris.setViewportView(tblBarangTerlaris);

        panelTerlaris.add(scrollTerlaris, java.awt.BorderLayout.CENTER);

        panelDuaTabel.add(panelTerlaris);

        panelSedikitTerjual.setBackground(new java.awt.Color(255, 255, 255));
        panelSedikitTerjual.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235))));
        panelSedikitTerjual.setLayout(new java.awt.BorderLayout());

        lblJudulSedikitTerjual.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblJudulSedikitTerjual.setForeground(new java.awt.Color(17, 24, 39));
        lblJudulSedikitTerjual.setText("BARANG PALING SEDIKIT TERJUAL");
        lblJudulSedikitTerjual.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 8, 0));
        panelSedikitTerjual.add(lblJudulSedikitTerjual, java.awt.BorderLayout.NORTH);

        tblBarangSedikitTerjual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Barang", "Qty Terjual", "Total Penjualan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBarangSedikitTerjual.setGridColor(new java.awt.Color(229, 231, 235));
        tblBarangSedikitTerjual.setRowHeight(28);
        scrollSedikitTerjual.setViewportView(tblBarangSedikitTerjual);

        panelSedikitTerjual.add(scrollSedikitTerjual, java.awt.BorderLayout.CENTER);

        panelDuaTabel.add(panelSedikitTerjual);

        panelBodyLaporan.add(panelDuaTabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBodyLaporan, java.awt.BorderLayout.CENTER);

        panelAksiLaporan.setBackground(new java.awt.Color(255, 255, 255));
        panelAksiLaporan.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20), javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(209, 213, 219))));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0);
        flowLayout2.setAlignOnBaseline(true);
        panelAksiLaporan.setLayout(flowLayout2);

        btnCetak.setBackground(new java.awt.Color(37, 99, 235));
        btnCetak.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setText("Cetak");
        btnCetak.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnCetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCetak.setPreferredSize(new java.awt.Dimension(100, 40));
        btnCetak.addActionListener(this::btnCetakActionPerformed);
        panelAksiLaporan.add(btnCetak);

        btnExportPDF.setBackground(new java.awt.Color(243, 244, 246));
        btnExportPDF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnExportPDF.setForeground(new java.awt.Color(55, 65, 81));
        btnExportPDF.setText("Export PDF");
        btnExportPDF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        btnExportPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportPDF.setPreferredSize(new java.awt.Dimension(110, 40));
        btnExportPDF.addActionListener(this::btnExportPDFActionPerformed);
        panelAksiLaporan.add(btnExportPDF);

        btnExportExcel.setBackground(new java.awt.Color(243, 244, 246));
        btnExportExcel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnExportExcel.setForeground(new java.awt.Color(55, 65, 81));
        btnExportExcel.setText("Export Excel");
        btnExportExcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        btnExportExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportExcel.setPreferredSize(new java.awt.Dimension(120, 40));
        btnExportExcel.addActionListener(this::btnExportExcelActionPerformed);
        panelAksiLaporan.add(btnExportExcel);

        btnTutupLaporanBawah.setBackground(new java.awt.Color(107, 114, 128));
        btnTutupLaporanBawah.setForeground(new java.awt.Color(255, 255, 255));
        btnTutupLaporanBawah.setText("Tutup");
        btnTutupLaporanBawah.setPreferredSize(new java.awt.Dimension(90, 40));
        btnTutupLaporanBawah.addActionListener(this::btnTutupLaporanBawahActionPerformed);
        panelAksiLaporan.add(btnTutupLaporanBawah);

        getContentPane().add(panelAksiLaporan, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilterHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterHariActionPerformed
        // TODO add your handling code here:
        Date hariIni = new Date();
        dateAwal.setValue(hariIni);
        dateAkhir.setValue(hariIni);
        tampilkanLaporan(hariIni, hariIni);
    }//GEN-LAST:event_btnFilterHariActionPerformed

    private void btnFilterMingguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterMingguActionPerformed
        // TODO add your handling code here:
        Calendar cal = Calendar.getInstance();
        Date hariIni = cal.getTime();
        cal.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);
        Date awalMinggu = cal.getTime();

        dateAwal.setValue(awalMinggu);
        dateAkhir.setValue(hariIni);
        tampilkanLaporan(awalMinggu, hariIni);
    }//GEN-LAST:event_btnFilterMingguActionPerformed

    private void btnFilterBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterBulanActionPerformed
        // TODO add your handling code here:
        Calendar cal = Calendar.getInstance();
        Date hariIni = cal.getTime();
        cal.set(Calendar.DAY_OF_MONTH, 1);
        Date awalBulan = cal.getTime();

        dateAwal.setValue(awalBulan);
        dateAkhir.setValue(hariIni);
        tampilkanLaporan(awalBulan, hariIni);
    }//GEN-LAST:event_btnFilterBulanActionPerformed

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here:
         Date awal = (Date) dateAwal.getValue();
        Date akhir = (Date) dateAkhir.getValue();
        tampilkanLaporan(awal, akhir);  
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {
        boolean berhasil = tblBarangTerlaris.print();
        if (!berhasil) {
            JOptionPane.showMessageDialog(this, "Pencetakan dibatalkan.");
        }
        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal mencetak: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
            "Fitur Export PDF akan tersedia pada update berikutnya.",
            "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExportPDFActionPerformed

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
            "Fitur Export Excel akan tersedia pada update berikutnya.",
            "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExportExcelActionPerformed

    private void btnTutupLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupLaporanActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnTutupLaporanActionPerformed

    private void btnTutupLaporanBawahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupLaporanBawahActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnTutupLaporanBawahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LaporanForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnFilterBulan;
    private javax.swing.JButton btnFilterHari;
    private javax.swing.JButton btnFilterMinggu;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JButton btnTutupLaporan;
    private javax.swing.JButton btnTutupLaporanBawah;
    private javax.swing.JSpinner dateAkhir;
    private javax.swing.JSpinner dateAwal;
    private javax.swing.JLabel lblDariTanggal;
    private javax.swing.JLabel lblJudulLaporan;
    private javax.swing.JLabel lblJudulSedikitTerjual;
    private javax.swing.JLabel lblJudulTerlaris;
    private javax.swing.JLabel lblJumlahTransaksi;
    private javax.swing.JLabel lblSampaiTanggal;
    private javax.swing.JLabel lblTotalPenjualan;
    private javax.swing.JPanel panelAksiLaporan;
    private javax.swing.JPanel panelBodyLaporan;
    private javax.swing.JPanel panelDuaTabel;
    private javax.swing.JPanel panelFilterLaporan;
    private javax.swing.JPanel panelHeaderWrapperLap;
    private javax.swing.JPanel panelJudulLaporan;
    private javax.swing.JPanel panelRingkasanLap;
    private javax.swing.JPanel panelSedikitTerjual;
    private javax.swing.JPanel panelTerlaris;
    private javax.swing.JScrollPane scrollSedikitTerjual;
    private javax.swing.JScrollPane scrollTerlaris;
    private javax.swing.JTable tblBarangSedikitTerjual;
    private javax.swing.JTable tblBarangTerlaris;
    // End of variables declaration//GEN-END:variables
}
